/*
01_create_database.sql
BD: MrLeeDB (SQL Server Express 2022 / 2019+)
*/

-- OPCIONAL (si querés recrear desde cero; OJO borra todo):
-- IF DB_ID(N'MrLeeDB') IS NOT NULL
-- BEGIN
--   ALTER DATABASE MrLeeDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
--   DROP DATABASE MrLeeDB;
-- END
-- GO

IF DB_ID(N'MrLeeDB') IS NULL
BEGIN
  CREATE DATABASE MrLeeDB;
END
GO

ALTER DATABASE MrLeeDB SET RECOVERY SIMPLE;
ALTER DATABASE MrLeeDB SET PAGE_VERIFY CHECKSUM;
GO
